listeners:
  - query_port: {{server.variables.port}}
    motd: ''
    host: 0.0.0.0:{{server.variables.port}}
    max_players: 100

servers:
  {% for server in servers %}
  {% unless server.type == "waterfall" %}
  {{server.id}}:
    motd: {{server.name}}
    address: localhost:{{server.variables.port}}
    restricted: {{server.variables.restricted}}
  {% endunless %}
  {% endfor %}

ip_forward: true
force_default_server: true
inject_commands: true
