name: Config_Controller
description: A simple command-line application.
version: 1.0.0-alpha
homepage: https://github.com/Samuel-Martineau/MC-Config-Controller

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  args: ^1.6.0
  http: ^0.12.2
  path: ^1.7.0
  web_scraper: ^0.0.6
  yamlicious: ^0.1.0
  yaml: ^2.2.1
  logger: ^0.9.1
  mustache_template: ^1.0.0+1

dev_dependencies:
  pedantic: ^1.9.0
