name: Build & Release

on:
  push:
    paths:
      - 'pubspec.yaml'
      - 'pubspec.lock'
      - 'environment_config.yaml'
      - 'lib/**'
      - 'bin/**'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      UPLOAD_URL: ${{ steps.create_release.outputs.upload_url }}
      VERSION: ${{ steps.project_version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v2
      - name: Install YQ
        run: sudo snap install yq
      - name: Read version from pubspec.yaml
        id: project_version
        run: echo ::set-output name=VERSION::$(yq r pubspec.yaml version)
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.project_version.outputs.VERSION }}
          release_name: Release ${{ steps.project_version.outputs.VERSION }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
  build:
    name: Build for  ${{ matrix.os-display-name }}
    runs-on: ${{ matrix.os }}
    needs: create-release

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        include:
          - os: ubuntu-latest
            os-display-name: linux
            output-file: config-controller-linux
          - os: macOS-latest
            os-display-name: macos
            output-file: config-controller-macos
          - os: windows-latest
            os-display-name: windows
            output-file: config-controller-windows
    steps:
      - uses: actions/checkout@v2
      - name: Install Dart
        uses: DanTup/gh-actions/setup-dart@v0.0.7
      - name: Install dependencies
        run: pub get
      - name: Generate environment config
        run: pub run environment_config:generate --build_version=${{ needs.create-release.outputs.VERSION }}
      - name: Build
        run: dart2native bin/main.dart -o ${{ matrix.output-file }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.output-file }}
          path: ${{ matrix.output-file }}
  create-release-assets:
    name: Create Release Assets for ${{ matrix.os-display-name }}
    runs-on: ubuntu-latest
    needs: [create-release, build]

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        include:
          - os: ubuntu-latest
            os-display-name: linux
            artifact-name: config-controller-linux
            output-file: config-controller
          - os: macOS-latest
            os-display-name: macos
            artifact-name: config-controller-macos
            output-file: config-controller
          - os: windows-latest
            os-display-name: windows
            artifact-name: config-controller-windows
            output-file: config-controller.exe

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.artifact-name }}
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: ${{ matrix.artifact-name }}
      - run: mv ${{ matrix.artifact-name }} ${{ matrix.output-file }}
      - run: chmod +x ${{ matrix.output-file }}
        if: ${{ matrix.os-display-name == 'linux' || matrix.os-display-name == 'macos' }}
      - run: zip ${{ matrix.os-display-name }}.zip ${{ matrix.output-file }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.UPLOAD_URL }}
          asset_path: ${{ matrix.os-display-name }}.zip
          asset_name: ${{ matrix.os-display-name }}.zip
          asset_content_type: application/zip
